### ISSUE TITLE
setdistinctparameter()

### ISSUE THREAD

**Issue by lrennels** [lrennels/mimi-page-2009.jl#2]
The `setdistinctparameter()` function in src/utils/mctools.jl now uses copied code from `set_leftover_params` in Mimi connections.jl.  We should break out the required portion (copied below) and create a separate function called by both.  

```
param_dims = parameter_dimensions(md, comp_name, param_name)
num_dims = length(param_dims)

if num_dims == 0    # scalar case
        set_external_scalar_param!(md, param_name, value)

else #array case
        if num_dims in (1, 2) && param_dims[1] == :time   
             value = convert(Array{md.number_type}, value)

             values = get_timestep_instance(md, eltype(value), num_dims, value)
                      
         else
              values = value
         end
         set_external_array_param!(md, param_name, values, param_dims)
end
```

One idea is to add methods to `set_external_param!` in Mimi.  Currently it has the following two methods:

```
function set_external_param!(md::ModelDef, name::Symbol, value::ModelParameter)
    md.external_params[name] = value
end

function set_external_param!(m::Model, name::Symbol, value::ModelParameter)
    set_external_param!(m.md, name, value)
    decache(m)
end
```

Perhaps we should add another set of methods here, one for `md::ModelDef` and one for `md::Model`  which handle the case where the `value` elements are of type `Number`, and then include the script below.   That way both the functions could just call `set_external_param!`.  

@rjplevin what do you think?

**Comment by rjplevin** [comment]
That sounds right to me!

**Comment by lrennels** [comment]
@rjplevin great.  For the type parameterization on `value` I would think we could start with `Union{Number, AbstractArray, Range, Tuple}` would work.  `Number` should handle all of the scalar cases, and then `{AbstractArray, Tuple, Range}` should handle the array cases.  Let me know if there is a more elegant way you'd advice, or other types I should include.

**Comment by rjplevin** [comment]
@lrennels, I assume that you mean one method will have parameter `value::Number`, and the other  `values::Union{AbstractArray, Range, Tuple}`. Is that right? (Anyway, that's what I was imagining.)

**Comment by lrennels** [comment]
Yep that should work!

**Comment by lrennels** [comment]
@rjplevin I've put out a small PR on Mimi for this.  Our runtests file doesn't test `set_leftover_params!`, but fund does use it, so `run_dependencies.jl` will check that for us now.  Take a look at see what you think.  I added some optional parameters, the diff should show why.
