### ISSUE TITLE
Repeat Reset in MCS

### ISSUE THREAD

**Issue by lrennels** [lrennels/mimi-page-2009.jl#5]
The portion of `@defmcs` that defines random variables is organized by component, each section setting the parameters for that component that need to be reset for the mcs run.  This means that some parameters are reset more than once, if they are used by more than one component.  Will this cause any unintende problems?  These cases are written documented in the comments using "repeat reset

**Comment by corakingdon** [comment]
@lrennels I think this won't cause any unintended problems. If we look at an example, such as the parameter :save_savingsrate, it gets set in the GDP component as well as the MarketDamages component. In the old code, it gets "randomized" twice, which is redundant, but it updates the external parameter within the model each time so whatever the second random value is will get used by both components, I think. I can test this tomorrow to be sure I understand how the randomizecomponent functions all work together.

**Comment by lrennels** [comment]
@cora I think you're right!  Only thing would be if there's a flag in the new mcs that doesn't like this, but I think for now it should be fine.

**Comment by corakingdon** [comment]
That being said, there's no need for us to set it twice, other than clarity of grouping values by components

**Comment by lrennels** [comment]
Yea I agree, there's really no need to do that, but I think if we keep the component organization for now then we'll want to.  That way we protect ourself against choosing a component to put it in, and then removing that component or something down the line.  We could also put a section up front with "variables in many components" or something ...
