### ISSUE TITLE
Setting Random Variable Arrays

### ISSUE THREAD

**Issue by lrennels** [lrennels/mimi-page-2009.jl#6]
We need to decide how we want to handle setting random variables when the variable is an array (such as a variable with a regional index).

**Comment by lrennels** [comment]
From PR conversation:

I see two ways to handle this:

Change this to set each array element separately
```
emitf_uncertaintyinBAUemissfactor[2]  = TriangularDist(0.8,1.2,1.0)
emitf_uncertaintyinBAUemissfactor[3]  = TriangularDist(0.8,1.2,1.0)
...
```
and so on, or

Allow a syntax like:
```
emitf_uncertaintyinBAUemissfactor[2:end]  = [
   TriangularDist(0.8,1.2,1.0),
   TriangularDist(0.8,1.2,1.0),
   ...
```
An advantage of the first approach is that we might use the Dimension type to convert from symbolic region names to indices, which would add clarity:

```
Main> reg = Dimension(["EU", "USA", "OECD","USSR","China","SEAsia","Africa","LatAmerica"])
Mimi.Dimension(DataStructures.OrderedDict{Union{AbstractString, Float64, Int64, Symbol},Int64}("EU"=>1,"USA"=>2,"OECD"=>3,"USSR"=>4,"China"=>5,"SEAsia"=>6,"Africa"=>7,"LatAmerica"=>8), String)

Main> reg["USSR"]
4
```

i.e.,

```
emitf_uncertaintyinBAUemissfactor[reg["USA"]]   = TriangularDist(0.8,1.2,1.0)
emitf_uncertaintyinBAUemissfactor[reg["OECD"]]  = TriangularDist(0.8,1.2,1.0)
```

**Comment by corakingdon** [comment]
@lrennels @rjplevin From my first pass at working on fund today, I think we should support the second suggested syntax if possible. Most of the fund MC parameters are structured as arrays of distributions, so it would be helpful to be able to use syntax such as:
`
aceiadd = [Normal(0.0,0.025), Normal(0.0,0.0375), Normal(0.0,0.025), ...]
`
instead of having to specify each element individually.

**Comment by rjplevin** [comment]
I agree that this would be slightly more convenient (and I'm willing to implement it!) but from a code maintenance perspective, I don't like the implicit ordering of distributions which must match the (unstated) order of regions. I'd opt for the more verbose, but more bullet-proof
```
emitf_uncertaintyinBAUemissfactor[reg["USA"]]   = TriangularDist(0.8,1.2,1.0)
emitf_uncertaintyinBAUemissfactor[reg["OECD"]]  = TriangularDist(0.8,1.2,1.0)
```
But we can also support both.

**Comment by lrennels** [comment]
I have the same hesitation about implicit ordering, could be an easy way to get a nasty bug :)

**Comment by corakingdon** [comment]
Definitely makes sense for clarity purposes to enforce explicit labeling. Maybe we can see what David thinks. Fund has about 100 distributional parameters, and over half are regional arrays so the body of the defmcs would get pretty long, but maybe I can organize them into separate files by component or something, then just 'include' them in the macro. Works either way, just depends on what we think is the cleanest!

**Comment by rjplevin** [comment]
How about both robustness and convenience? :-)  For example, we could have explicit support for distributions vectors in `@defmcs`, where we define pairs with the first arg being the dimension label and the second arg being the distribution, i.e., 
```
some_array_param = [
   "USA"  => TriangularDist(0.8,1.2,1.0),
   "OECD" => TriangularDist(0.8,1.2,1.0),
   ...
]
```
I think this generalizes ok beyond regions.

**Comment by corakingdon** [comment]
@rjplevin I like that a lot!  

We should also think about what we want the syntax to be for when an array parameter has two dimensions (i.e. time x regions, or in the case of fund there is one that is regions x regions)

**Comment by corakingdon** [comment]
maybe we want to add a function to Mimi for loading in parameter definitions from csvs. The ones for FUND are defined in long format, with the first column being the dimension labels, a second column of dimension labels if its two-dimensional, and the final column is the distribution definition. 

1-D example: https://github.com/fund-model/fund/blob/next/data/aceiadd.csv
2-D example: https://github.com/fund-model/fund/blob/next/data/migrate.csv

I'm going to end up writing a function to load all of fund's data files into whichever format we decide we want for the mcs macro, and then it's a question of whether that function is just specifically useful to fund, or if we want to have it be general Mimi functionality.

**Comment by rjplevin** [comment]
For multiple dimensions, we could do:
```
some_array_param = [
      ["USA", "USA"]  => TriangularDist(0.8,1.2,1.0),
      ["USA", "CAN"]  => TriangularDist(0.8,1.2,1.0),
      ...
]
```
and support loading from a CSV file to produce this structure:
```
some_array_param = load("whatever/filename.csv")
```
where the `@defmcs` macro would load the data and return the structure above. 

@cora, does this work for you?
